In [65]:
import numpy as np

x= np.array([1,2,3,4])

In [66]:
y=np.array([[1,2,4,5],[2,2,4,55]])

In [67]:
x.size;

In [68]:
# get dimension
x.ndim
y.ndim

2

In [69]:
# Get Shape
x.shape
y.shape

(2, 4)

In [70]:
# Get type and Memory it is using
x.dtype 

#itemsize
x.itemsize # in bytes

# total element
x.size

4

In [71]:
# Access Element [row ,column ]
y[0,3]

5

In [72]:
# get a specific row 
y[1,:]


array([ 2,  2,  4, 55])

In [73]:
# get a specific col.
y[:,2]

array([4, 4])

In [83]:


zero3d= np.zeros((2,2,2),dtype ="int32")
print(zero3d)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [90]:
# full method just like fill method in JS
np.full((2,2),99,dtype="float32") # (2,2) is a shape.

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [94]:
#full like. : reuse shape of other already build array
np.full_like(y,99)
#or
np.full(y.shape,99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [95]:
#random 
np.random.rand(y.size)

array([0.51289779, 0.29569995, 0.06509954, 0.97698135, 0.3713907 ,
       0.85818996, 0.52601012, 0.00712565])

In [109]:
np.random.randint((100,150),size=(2,2))

array([[ 6, 65],
       [ 7, 11]])

In [ ]:
# identity Matrix
