In [1]:
import numpy as np

x= np.array([1,2,3,4])

In [2]:
y=np.array([[1,2,4,5],[2,2,4,55]])
y

array([[ 1,  2,  4,  5],
       [ 2,  2,  4, 55]])

In [3]:
x.size;

In [4]:
# get dimension
x.ndim
y.ndim

2

In [5]:
# Get Shape
x.shape
y.shape

(2, 4)

In [6]:
# Get type and Memory it is using
x.dtype 

#itemsize
x.itemsize # in bytes

# total element
x.size

4

In [7]:
# Access Element [row ,column ]
y[0,3]

5

In [8]:
# get a specific row 
y[1,:]


array([ 2,  2,  4, 55])

In [9]:
# get a specific col.
y[:,2]

array([4, 4])

In [10]:


zero3d= np.zeros((2,2,2),dtype ="int32")
print(zero3d)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [11]:
# full method just like fill method in JS
np.full((2,2),99,dtype="float32") # (2,2) is a shape.

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [12]:
#full like. : reuse shape of other already build array
np.full_like(y,99)
#or
np.full(y.shape,99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [13]:
#random 
np.random.rand(y.size)

array([0.56859446, 0.98199292, 0.34967792, 0.30289948, 0.08143041,
       0.97870059, 0.38299104, 0.37409354])

In [20]:
np.random.randint((100,150),size=(2,2))

array([[  9, 146],
       [  9,  16]])

In [21]:
# identity Matrix
np.identity(10) //10*10
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
a=np.array([1,2,3])
b=np.array([10,11,12])
print(a+b)
print(a-b)
print(a*b)
# dot product
print(np.dot(a,b))



[11 13 15]
[-9 -9 -9]
[10 22 36]
68


In [23]:
#Transpose
a=np.array([[1,23,12],[1,2,2],[2,1,1]])
a.T

array([[ 1,  1,  2],
       [23,  2,  1],
       [12,  2,  1]])

In [24]:
a.T

array([[ 1,  1,  2],
       [23,  2,  1],
       [12,  2,  1]])

In [32]:
np.eye(4).T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
A= np.array([[1,2,3],[1,2,3],[1,2,3]])
b= [1,2,3];
def magic(A,B):
    for x in range(0,len(B)):
        A[x]=(A[x]*B[x])
    return A;
magic(A,b)
        

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])